### ISSUE TITLE
The clock on the panel is too close to the edge

### ISSUE THREAD

**Issue by Jacalz** [solus-project/mate-desktop-branding#3]
The clock is too close to the edge and it looks quite janky. My suggestion would be to move it to the left with the same amount of pixels as the length between the wifi/lan icon and the left most number in the clock.
![screenshot at 2017-12-06 19-17-10](https://user-images.githubusercontent.com/25466657/33677786-3345b670-daba-11e7-819f-ccd70d6baf14.png)

**Comment by ghost** [comment]
can I manually fix this myself by adding a spacer or anything? it's so annoying to look at

**Comment by Jacalz** [comment]
I am no longer using Mate and don't know if this is a problem any more. As Solus are planning on moving to Xfce instead, I'll close this.
